version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  
  # Taiga settings
  TAIGA_VERSION: "${TAIGA_VERSION}"
  TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
  TAIGA_SITES_SCHEME: "${TAIGA_SITES_SCHEME}"
  TAIGA_SITES_DOMAIN: "${TAIGA_SITES_DOMAIN}"
  TAIGA_SUBPATH: "" # "" or "/subpath"
  
  # Email settings
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_PORT: "${EMAIL_PORT}"
  
  # Rabbit settings
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASS: "${RABBITMQ_PASS}"
  CELERY_ENABLED: "${CELERY_ENABLED}"
  ENABLE_TELEMETRY: "False"
  
  # LDAP settings
  LDAP_ENABLED: "${LDAP_ENABLED}"
  LDAP_SERVER: "${LDAP_SERVER}"
  LDAP_PORT: "${LDAP_PORT}"
  LDAP_START_TLS: "${LDAP_START_TLS}"
  LDAP_SEARCH_BASE: "${LDAP_SEARCH_BASE}"
  LDAP_BIND_DN: "${LDAP_BIND_DN}"
  LDAP_BIND_PASSWORD: "${LDAP_BIND_PASSWORD}"
  LDAP_CERT_PATH: "${LDAP_CERT_PATH}"

networks:
  network:
    driver: bridge
  nginx:
    external:
      name: nginx-default_network
  mail:
    external:
      name: mail_network

services:
  taiga-db:
    image: postgres:12.3
    restart: always
    hostname: "${POSTGRES_HOST}"
    container_name: 'taiga-db'
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /srv/taiga/db/data:/var/lib/postgresql/data
    networks:
      - network

  taiga-back:
    image: registry.bjoern-freund.de/taiga-back
    restart: always
    hostname: 'taiga-back'
    container_name: 'taiga-back'
    environment: *default-back-environment
    volumes:
      - /srv/taiga/back/static-data:/taiga-back/static
      - /srv/taiga/back/media-data:/taiga-back/media
      - "${LDAP_CERT_PATH}:${LDAP_CERT_PATH}"
    networks:
      - network
      - mail
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: registry.bjoern-freund.de/taiga-back
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    restart: always
    hostname: 'taiga-async'
    container_name: 'taiga-async'
    environment: *default-back-environment
    volumes:
      - /srv/taiga/back/static-data:/taiga-back/static
      - /srv/taiga/back/media-data:/taiga-back/media
    networks:
      - network
      - mail
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    hostname: 'taiga-async-rabbitmq'
    container_name: 'taiga-async-rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    networks:
      - network

  taiga-front:
    image: "taigaio/taiga-front:${TAIGA_VERSION}"
    restart: always
    hostname: 'taiga-front'
    container_name: 'taiga-front'
    environment:
      TAIGA_URL: "${TAIGA_SITES_SCHEME}://${TAIGA_SITES_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "wss://${TAIGA_SITES_DOMAIN}"
      TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
    networks:
      - network

  taiga-events:
    image: "taigaio/taiga-events:${TAIGA_VERSION}"
    restart: always
    hostname: 'taiga-events'
    container_name: 'taiga-events'
    environment:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
      CELERY_ENABLED: "${CELERY_ENABLED}"
    networks:
      - network
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    hostname: 'taiga-events-rabbitmq'
    container_name: 'taiga-events-rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: taiga
    networks:
      - network

  taiga-protected:
    image: "taigaio/taiga-protected:${TAIGA_VERSION}"
    restart: always
    hostname: 'taiga-protected'
    container_name: 'taiga-protected'
    environment:
      MAX_AGE: 360
      SECRET_KEY: "${TAIGA_SECRET_KEY}"
    networks:
      - network

  taiga-gateway:
    image: nginx:1.19-alpine
    restart: always
    hostname: 'taiga-gateway'
    container_name: 'taiga-gateway'
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - /srv/taiga/back/static-data:/taiga/static
      - /srv/taiga/back/media-data:/taiga/media
    networks:
      - network
      - nginx
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
